version: '3'
services:
  eda:
    build: .
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "eda-2024-secret"
      DATABASE_URL: "postgresql://postgres.eysscksbdwggivvgseci:VHH.ba5Xkfz7Q%23h@aws-0-eu-west-2.pooler.supabase.com:6543/postgres"
    restart: always